apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  template:
    spec:
      containers:
      - name: {{.Name}}
        env:
        - name: PROJECT_ENV
          value: "dev"
        - name: MYSQL_DBNAME
          value: "{{.Name}}-dev"